config/routes.rb
GameHall::Application.routes.draw do

	

	namespace :tmu_admin do
		resources :users do
			member do
				patch :update_password, :reset_password
			end
		end

		resource :user_session
		resource :password_reset, :only => [:create, :edit, :update]
		resources :active_devices
		resources :apps 
		resources :rooms 
		resources :players

		post "active_devices/data" => "active_devices#data"
		post "apps/data" => "apps#data"
		post "rooms/data" => "rooms#data"
		post "players/data" => "players#data"
		post "users/data" => "users#data"

		post "rooms/search" => "rooms#search"

		get "/dashboard" => "tmu_admin#dashboard"
		root :to => "tmu_admin#index"
	end

	get "download/test" => "download#test"
	get "download/package" => "download#package"
	get "download/image" => "download#image"
	get "active/device" => "active#device"
	
	post "regist/quick" => "regist#quick"
	post "regist/normal" => "regist#normal"
	post "login/login" => "login#login"
	post "login/:appid/app" => "login#app"
	post "apps" => "apps#list"
	post "apps/:appid/rooms" => "apps#rooms"
	post "deposit/cash" => "deposit#cash"
	
	get "/admin" => redirect("/tmu_admin")
end

app/models/tmu_admin/app.rb
include TmuAdminHelper
module TmuAdmin
  class App < ActiveRecord::Base
    def summary
      {
        :appid => id,
        :appName => name,
        :icon => image_url,
        :url => package_url,
        :ip => "192.168.0.6",
        :port => 6002
      }
    end

    def package_url
      "#{hostname}/download/package?pid=#{Digest::MD5::hexdigest(Time.now.to_s)}#{id}"
    end

    def image_url
      "#{hostname}/download/image?pid=#{Digest::MD5::hexdigest(Time.now.to_s)}#{id}"
    end
  end
end

app/models/tmu_admin/room.rb
module TmuAdmin
  class Room < ActiveRecord::Base
    def summary
      {
          :id => id,
          :name => name,
          :backgroud => backgroud||"",
          :total => total_lest,
          :single => single_lest
      }
    end
  end
end

app/models/tmu_admin/user.rb
include TmuAdminHelper
module TmuAdmin
	$ACCESS_LEVEL_ADMIN = 0
	$ACCESS_LEVEL_USER = 10
	class User < ActiveRecord::Base
		self.table_name = "tmu_admin_users"
		acts_as_authentic { |c| c.validate_email_field = false }

		attr_accessor :notify_of_new_password
		after_create :send_create_notification
		after_update :send_update_notification


		def send_create_notification
			TmuAdmin::Notification.new_user_information(email_address, self, hostname, @password).deliver
		end

		def send_update_notification
			if notify_of_new_password
				notify_of_new_password = false
				TmuAdmin::Notification.generate_new_password(email_address, self, hostname, @password).deliver
			end
		end

		def send_password_reset_instructions
			reset_perishable_token!
			TmuAdmin::Notification.password_reset_instructions(email_address, self, hostname).deliver
		end
		def is_admin?
			access_level == $ACCESS_LEVEL_ADMIN
		end

	end
end

app/models/tmu_admin/user_session.rb
module TmuAdmin
  class UserSession < Authlogic::Session::Base
    include ActiveModel::Conversion
    def persisted?
      false
    end
  end
end

app/controllers/tmu_admin/active_devices_controller.rb
module TmuAdmin
  class ActiveDevicesController < TmuAdmin::TmuAdminController
   layout "tmu_admin/layouts/application"
   layout "tmu_admin/layouts/application"

   before_action :set_active_device, only: [:show, :destroy]
   def index
   end

   def data
    condition = "1=1"
    total = ActiveDevice.where(condition).count
    devices = ActiveDevice.where(condition).paginate(:page => params[:page]||1, :per_page => params[:rows]||20)
    data_json = {
      :total => total,
      :rows => devices
    }
    render :json => data_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_device
      @active_device = ActiveDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_device_params
      params.require(:active_device).permit(:device, :serail)
    end
  end
end

app/controllers/tmu_admin/apps_controller.rb
module TmuAdmin
  class AppsController < TmuAdmin::TmuAdminController
    layout "tmu_admin/layouts/application"

    before_action :set_app, only: [:show, :edit, :update, :destroy]

    # GET /apps
    # GET /apps.json
    def index
    end


    def data
      condition = "1=1"
      total = TmuAdmin::App.where(condition).count
      apps = TmuAdmin::App.where(condition).paginate(:page => params[:page]||1, :per_page => params[:rows]||20)
      data_json = {
          :total => total,
          :rows => apps
      }
      render :json => data_json
    end

    def new
      @app = TmuAdmin::App.new
    end

    # GET /apps/1/edit
    def edit
    end

    # POST /apps
    # POST /apps.json
    def create
      @app = TmuAdmin::App.new(app_params)
      if @app.save
        render :json => {}
      else
        error_messages = @app.errors.full_messages.collect { |error_message| "<li>" + error_message + "</li>" }

        render :json => {:errorMsg => "<ul>" + error_messages.join("") + "</ul>"}
      end
    end

    # PATCH/PUT /apps/1
    # PATCH/PUT /apps/1.json
    def update
      respond_to do |format|
        if @app.update(app_params)
          format.html { redirect_to @app, notice: 'App was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @app.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /apps/1
    # DELETE /apps/1.json
    def destroy
      @app.destroy
      respond_to do |format|
        format.html { redirect_to apps_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = TmuAdmin::App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      icon_obj = params[:tmu_admin_app][:icon]
      package_obj = params[:tmu_admin_app][:url]

      icon_suffix = icon_obj.original_filename.split(".").last
      package_suffix = package_obj.original_filename.split(".").last

      icon_file_path = "#{Rails.root}/public/images/apk/icons/#{Digest::MD5.hexdigest(Time.now.to_i.to_s)}.#{icon_suffix}"
      package_file_path = "#{Rails.root}/public/files/apk/packages/#{Digest::MD5.hexdigest(Time.now.to_s)}.#{package_suffix}"

      icon_url = "/public/images/apk/icons/#{Digest::MD5.hexdigest(Time.now.to_s)}.#{icon_suffix}"
      package_url = "/public/images/apk/packages/#{Digest::MD5.hexdigest(Time.now.to_s)}.#{package_suffix}"


      FileUtils.mkdir_p File.dirname(icon_file_path) unless File.exists?(icon_file_path)
      FileUtils.mkdir_p File.dirname(package_file_path) unless File.exists?(package_file_path)

      File.open(icon_file_path, "wb") { |icon| icon.write(icon_obj.read) }
      File.open(package_file_path, "wb") { |apk| apk.write(package_obj.read) }

      params[:tmu_admin_app][:icon] = icon_url
      params[:tmu_admin_app][:url] = package_url

      params.require(:tmu_admin_app).permit(:name, :icon, :url)
    end
  end
end

app/controllers/tmu_admin/password_resets_controller.rb
module TmuAdmin
  class PasswordResetsController < TmuAdmin::TmuAdminController
    
    unloadable
    
    skip_before_filter :authorise
    before_filter :load_user_using_perishable_token, :only => [:edit, :update]

    layout "tmu_admin/layouts/login"
    
    def create
      users = Casein::User.where(:email => params[:recover_email]).all

      if users.length > 0
        users.each do |user|
          user.send_password_reset_instructions
        end

        if users.length > 1
          flash[:notice] = "Multiple accounts were found. Emails have been sent to " + params[:recover_email] + " with instructions on how to reset your passwords"
        else
          flash[:notice] = "An email has been sent to " + params[:recover_email] + " with instructions on how to reset your password"
        end
      else
        flash[:warning] = "There is no user with that email"
      end

      redirect_to new_casein_user_session_url
    end

    def edit
      render
    end

    def update
      
      if params[:casein_user][:password].empty? || params[:casein_user][:password_confirmation].empty?
        flash.now[:warning] = "A field has been left empty"
      else
        
        @reset_user.password = params[:casein_user][:password]
        @reset_user.password_confirmation = params[:casein_user][:password_confirmation]
        
        if @reset_user.save
          flash[:notice] = "Password successfully updated"
          redirect_to new_casein_user_session_url
          return
        end
      end
      
      render :action => :edit
    end

    private
    
    def load_user_using_perishable_token
      
      @reset_user = Casein::User.find_using_perishable_token params[:token]
      
      unless @reset_user
        flash[:warning] = "Your account could not be located. Try to copy and paste the URL directly from the email."
        redirect_to new_casein_user_session_url
      end
    end
  end
end

app/controllers/tmu_admin/players_controller.rb
module TmuAdmin
  class PlayersController < TmuAdmin::TmuAdminController
    layout "tmu_admin/layouts/application"

    def index
    end

    def data
      condition = "1=1"
      total = Player.where(condition).count
      players = Player.where(condition).paginate(:page => params[:page]||1, :per_page => params[:rows]||20)
      data_json = {
        :total => total,
        :rows => players
      }
      render :json => data_json
    end
  end
end

app/controllers/tmu_admin/rooms_controller.rb
module TmuAdmin
  class RoomsController < TmuAdmin::TmuAdminController
    before_action :set_room, only: [:show, :edit, :update, :destroy]
    layout "tmu_admin/layouts/application"
    
    def index
      @appid = params[:app]||0
      @apps = TmuAdmin::App.all
    end


    def data
      condition = "appid = #{params[:app]}"
      total = TmuAdmin::Room.where(condition).count
      rooms = TmuAdmin::Room.where(condition).paginate(:page => params[:page]||1, :per_page => params[:rows]||20)
      data_json = {
        :total => total,
        :rows => rooms
      }
      render :json => data_json
    end

    def search
      redirect_to :action => :index,:app => params[:app]
    end

    def show
    end

    def new
      @room = TmuAdmin::Room.new
      @apps = TmuAdmin::App.all
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms
    # POST /rooms.json
    def create
      @room = TmuAdmin::Room.new(room_params)

      if @room.save
        render :json => {}
      else
        error_messages = @room.errors.full_messages.collect { |error_message| "<li>" + error_message + "</li>" }

        render :json => {:errorMsg => "<ul>" + error_messages.join("") + "</ul>"}
      end
    end

    # PATCH/PUT /rooms/1
    # PATCH/PUT /rooms/1.json
    def update
      respond_to do |format|
        if @room.update(room_params)
          format.html { redirect_to @room, notice: 'Room was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /rooms/1
    # DELETE /rooms/1.json
    def destroy
      @room.destroy
      respond_to do |format|
        format.html { redirect_to rooms_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = TmuAdmin::Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:appid,:name,:backgroud,:total_lest,:single_lest)
    end
  end
end

app/controllers/tmu_admin/tmu_admin_controller.rb
module TmuAdmin
	class TmuAdminController < ApplicationController
		unloadable

		layout "tmu_admin/layouts/main"

		before_filter :authorise

		def index		
			redirect_to dashboard_url
		end

		def dashboard
			@tmu_admin_page_title = "首页"
      #render :json => {}
		end

		private
		def authorise    
			unless current_user
				session[:return_to] = request.fullpath
				redirect_to new_tmu_admin_user_session_url
				return false
			end
		end

		def current_user_session
			return @current_user_session if defined?(@current_user_session)
			@current_user_session = TmuAdmin::UserSession.find
		end

		def current_user
			return @session_user if defined?(@session_user)
			@session_user = current_user_session && current_user_session.user
		end

		def needs_admin
			unless @session_user.is_admin?
				redirect_to :controller => :tmu_admin, :action => :index
			end
		end


		def redirect_back_or_default(default)
			redirect_to(session[:return_to] || default)
			session[:return_to] = nil
		end
	end
end

app/controllers/tmu_admin/user_sessions_controller.rb
module TmuAdmin
	class UserSessionsController < TmuAdmin::TmuAdminController
		#unloadable

		skip_before_filter :authorise, :only => [:new, :create]
		before_filter :requires_no_session_user, :except => [:destroy]

		layout "tmu_admin/layouts/login"

		def new
			@user_session = TmuAdmin::UserSession.new
		end

		def create
			@user_session = TmuAdmin::UserSession.new params[:tmu_admin_user_session]
			if @user_session.save
				flash[:notice] = "Login successful"
				redirect_back_or_default(:controller => :tmu_admin, :action => :dashboard)
			else
				render :action => :new
			end
		end

		def destroy
			current_user_session.destroy
			flash[:notice] = "Logout successful"
			redirect_back_or_default new_tmu_admin_user_session_url
		end

		private

		def requires_no_session_user
			if current_user
				redirect_to :controller => :tmu_admin, :action => :index
			end
		end
	end
end

app/controllers/tmu_admin/users_controller.rb
module TmuAdmin
	class UsersController < TmuAdmin::TmuAdminController

		  layout "tmu_admin/layouts/application"

		before_filter :needs_admin, :except => [:show, :destroy, :update, :update_password]
		before_filter :needs_admin_or_current_user, :only => [:show, :destroy, :update, :update_password]
		
		def index
		end

		def data
			condition = "1=1"
			total = TmuAdmin::User.where(condition).count
			players = TmuAdmin::User.where(condition).paginate(:page => params[:page]||1, :per_page => params[:rows]||20)
			data_json = {
				:total => total,
				:rows => players
			}
			render :json => data_json
		end
		
		def new
			@casein_user = TmuAdmin::User.new
		end
		
		def create
			@tmu_admin_user = TmuAdmin::User.new casein_user_params
			
			if @tmu_admin_user.save
				flash[:notice] = "An email has been sent to " + @tmu_admin_user.name + " with the new account details"
				redirect_to tmu_admin_users_path
			else
				flash.now[:warning] = "There were problems when trying to create a new user"
				render :action => :new
			end
		end
		
		def show
			@tmu_admin_user = TmuAdmin::User.find params[:id]
		end
		
		def update
			@tmu_admin_user = TmuAdmin::User.find params[:id]

			if @tmu_admin_user.update_attributes tmu_admin_user_params
				flash[:notice] = @tmu_admin_user.name + " has been updated"
			else
				flash.now[:warning] = "There were problems when trying to update this user"
				render :action => :show
				return
			end
			
			if @session_user.is_admin?
				redirect_to tmu_admin_user_users_path
			else
				redirect_to :controller => :tmu_admin, :action => :index
			end
		end
		
		def update_password
			@tmu_admin_user = TmuAdmin::User.find params[:id]
			
			if @tmu_admin_user.valid_password? params[:form_current_password]
				if @tmu_admin_user.update_attributes tmu_admin_user_params
					flash.now[:notice] = "Your password has been changed"
				else
					flash.now[:warning] = "There were problems when trying to change the password"
				end
			else
				flash.now[:warning] = "The current password is incorrect"
			end
			
			render :action => :show
		end
		
		def reset_password
			@tmu_admin_user = TmuAdmin::User.find params[:id]
			
			@tmu_admin_user.notify_of_new_password = true unless @tmu_admin_user.id == @session_user.id
			
			if @tmu_admin_user.update_attributes tmu_admin_user_params
				if @tmu_admin_user.id == @session_user.id
					flash.now[:notice] = "Your password has been reset"
				else    
					flash.now[:notice] = "Password has been reset and " + @tmu_admin_user.name + " has been notified by email"
				end
				
			else
				flash.now[:warning] = "There were problems when trying to reset this user's password"
			end
			render :action => :show
		end
		
		def destroy
			user = TmuAdmin::User.find params[:id]
			if user.is_admin? == false || TmuAdmin::User.has_more_than_one_admin
				user.destroy
				flash[:notice] = user.name + " has been deleted"
			end
			redirect_to casein_users_path
		end

		private

		def tmu_admin_user_params
			params.require(:casein_user).permit(:login, :name, :email, :time_zone, :access_level, :password, :password_confirmation)
		end
	end
end

app/helpers/tmu_admin_helper.rb
#encoding: utf-8
module TmuAdminHelper
	def website_name
		"天幕科技"
	end

	def email_address
		'313423716@qq.com'
	end

	def hostname
		'http://192.168.0.6:3000'
	end

	def dashboard_url
		"/tmu_admin/dashboard"
	end
end

app/views/tmu_admin/layouts/_left_navigation.html.erb
<div class="easyui-accordion" data-options="fit:true,border:false">
	<div data-options="iconCls:'icon-folder-doc',title:'产品管理'">
		<a href="javascript:void(0);" src="/tmu_admin/players" data-options="plain:true,iconCls:'icon-runner'" class="cs-navi-tab easyui-linkbutton">用户管理</a>
		<a href="javascript:void(0);" src="/tmu_admin/active_devices" data-options="plain:true"  iconCls="icon-runner" class="cs-navi-tab easyui-linkbutton">设备管理</a>
		<a href="javascript:void(0);" src="/tmu_admin/apps" data-options="plain:true"  iconCls="icon-runner" class="cs-navi-tab easyui-linkbutton">应用管理</a>
		<a href="javascript:void(0);" src="/tmu_admin/rooms" data-options="plain:true"  iconCls="icon-runner" class="cs-navi-tab easyui-linkbutton">房间管理</a>
	</div>
	<div data-options="iconCls:'icon-folder-doc',title:'系统配置'">
		<a href="javascript:void(0);" src="/tmu_admin/users" data-options="plain:true"  iconCls="icon-runner" class="cs-navi-tab easyui-linkbutton">在线奖励配置</a>
		<a href="javascript:void(0);" src="/tmu_admin/users" data-options="plain:true"  iconCls="icon-runner" class="cs-navi-tab easyui-linkbutton">系统用户管理</a>
	</div>
</div>

app/views/tmu_admin/layouts/application.html.erb
<html>
<head>
	<title>天幕科技</title>
	<%= stylesheet_link_tag "tmu_admin/themes/default/easyui"%>
	<%= stylesheet_link_tag "tmu_admin/themes/icon"%>
	<%= stylesheet_link_tag "tmu_admin/themes/main"%>
	<%= javascript_include_tag "application" %>
	<script type="text/javascript">
	$(function(){
		$(window).resize(function(){
			$('#main-layout').layout('resize');
		});
	});
	</script>
</head>
<body>
	<div data-options="region:'center'">
		<%=yield%>
	</div>
</body>
</html>

app/views/tmu_admin/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>天幕科技</title>
  <%= stylesheet_link_tag "tmu_admin/themes/default/easyui" %>
  <%= stylesheet_link_tag "tmu_admin/themes/icon" %>
  <%= stylesheet_link_tag "tmu_admin/themes/main" %>
  <%= javascript_include_tag "application" %>
  <style type="text/css">
      table {
          font-family: "微软雅黑";
          padding: 0;
          margin: 0 auto;
          border-collapse: collapse;
          margin-top: 20px;
      }

      td {
          background: #fff;
          font-size: 12px;
          padding: 3px 3px 3px 8px;
          color: #4f6b72;
      }

      input {
          width: 150px;
          border: 1px solid #ccc;
          padding: 2px;
      }
  </style>
  <script type="text/javascript">

      var loginDialog;
      var loginForm;

      $(document).ready(function () {

          loginDialog = $("#loginDialog").dialog({
              closable: false,
              cache: false,
              modal: true,
              buttons: [
                  {
                      text: "登录",
                      handler: function () {
                          loginFrom.submit();
                      }
                  }
              ]
          });


          loginFrom = $("#new_tmu_admin_user_session").form({
              success: function (data) {
                  loginDialog.dialog("close");
                  location.reload();
              }
          });

      });
  </script>
</head>
<body>
<div id="loginDialog" title="用户登录" style="width:300px;height:180px;">
  <%= yield %>
</div>
</body>
</html>

app/views/tmu_admin/layouts/main.html.erb
<html>
<head>
  <title>天幕科技</title>
  <%= stylesheet_link_tag "tmu_admin/themes/default/easyui" %>
  <%= stylesheet_link_tag "tmu_admin/themes/icon" %>
  <%= stylesheet_link_tag "tmu_admin/themes/main" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">
  $(function () {
    $(window).resize(function () {
      $('#main-layout').layout('resize');
    });
  });
  </script>
</head>
<body class="easyui-layout">
  <div data-options="region:'north',border:false" style="height:50px; padding-left:20px;line-height:50px;">
    <div style="float:right;padding-right: 100px"><%= link_to '退 出', tmu_admin_user_session_path, :method => "delete", :data =>{:confirm => "您确定要退出吗？" } %></div>
    <div style="height:50px;line-height:50px;float:left;font-size:30px;">天幕管理平台</div>
  </div>
  <div data-options="region:'west',title:'导航菜单',iconCls:'icon-settings'" style="width:200px;">
    <%= render :partial => '/tmu_admin/layouts/left_navigation' %>
  </div>
  <div data-options="region:'center'">
    <div id="tabs" class="easyui-tabs" data-options="fit:true,border:false">
      <%= yield %>
    </div>
    <div id="mm" class="easyui-menu 您确定要退出吗？cs-tab-menu">
      <div id="mm-tabupdate">刷新</div>
      <div class="menu-sep"></div>
      <div id="mm-tabclose">关闭当前标签</div>
      <div id="mm-tabcloseright">关闭右侧标签</div>
      <div id="mm-tabcloseleft">关闭左侧标签</div>
      <div id="mm-tabcloseother">关闭其他标签</div>
      <div id="mm-tabcloseall">关闭全部标签</div>
      <div id="mm-exit">退出</div>
    </div>
    <div region="south" style="text-align:center;height:30px;background:#95B8E7;padding:10px">
      Copyright © 2010-2013 www.tmu.com
    </div>
  </div>
</body>
</html>